services:

  smartcast-backend:
    build:
      context: ./backend
    container_name: smartcast-backend-dev

    ports:
      - "8080:8080"

    volumes:
      - ./backend:/app
      - ~/.m2:/root/.m2

    command: sh -c "./mvnw install -DskipTests && ./mvnw spring-boot:run -pl app"

    environment:
      - SPRING_PROFILES_ACTIVE=dev

  smartcast-frontend:
    build:
      context: ./frontend
    container_name: smartcast-frontend-dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    environment:
      - VITE_API_URL=http://localhost:8080