--liquibase formatted sql

--changeset smartcast:001-create-base-schema splitStatements:true
--comment: Base schema for users, materials, files, transcripts and processing jobs.

CREATE TABLE media_asset (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bucket VARCHAR(255) NOT NULL,
    object_key VARCHAR(1024) NOT NULL,
    original_name VARCHAR(255),
    type VARCHAR(32) NOT NULL,
    content_type VARCHAR(100) NOT NULL,
    size_bytes BIGINT NOT NULL,

    CONSTRAINT uq_media_asset_location UNIQUE (bucket, object_key),
    CONSTRAINT ck_media_asset_type CHECK (
        type IN ('ORIGINAL_AUDIO', 'STREAM_AUDIO', 'COVER', 'AVATAR')
    ),
    CONSTRAINT ck_media_asset_size CHECK (size_bytes >= 0)
);

CREATE TABLE app_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    keycloak_id VARCHAR(255) NOT NULL,
    display_name VARCHAR(100) NOT NULL,
    bio VARCHAR(1000),
    avatar_id BIGINT,

    CONSTRAINT uq_app_user_keycloak_id UNIQUE (keycloak_id),
    CONSTRAINT uq_app_user_avatar UNIQUE (avatar_id),
    CONSTRAINT fk_app_user_avatar FOREIGN KEY (avatar_id)
        REFERENCES media_asset (id) ON DELETE RESTRICT
);

CREATE TABLE category (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(1000),

    CONSTRAINT uq_category_name UNIQUE (name)
);

CREATE TABLE tag (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,

    CONSTRAINT uq_tag_name UNIQUE (name)
);

CREATE TABLE material (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author_id BIGINT NOT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    type VARCHAR(32) NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'DRAFT',
    category_id BIGINT NOT NULL,
    source_audio_id BIGINT,
    stream_audio_id BIGINT,
    cover_id BIGINT,
    duration_ms BIGINT,
    media_version INTEGER NOT NULL DEFAULT 1,

    CONSTRAINT fk_material_author FOREIGN KEY (author_id)
        REFERENCES app_user (id) ON DELETE RESTRICT,
    CONSTRAINT fk_material_category FOREIGN KEY (category_id)
        REFERENCES category (id) ON DELETE RESTRICT,
    CONSTRAINT fk_material_source_audio FOREIGN KEY (source_audio_id)
        REFERENCES media_asset (id) ON DELETE RESTRICT,
    CONSTRAINT fk_material_stream_audio FOREIGN KEY (stream_audio_id)
        REFERENCES media_asset (id) ON DELETE RESTRICT,
    CONSTRAINT fk_material_cover FOREIGN KEY (cover_id)
        REFERENCES media_asset (id) ON DELETE RESTRICT,
    CONSTRAINT uq_material_source_audio UNIQUE (source_audio_id),
    CONSTRAINT uq_material_stream_audio UNIQUE (stream_audio_id),
    CONSTRAINT uq_material_cover UNIQUE (cover_id),
    CONSTRAINT ck_material_type CHECK (type IN ('PODCAST', 'AUDIOBOOK')),
    CONSTRAINT ck_material_status CHECK (
        status IN (
            'DRAFT', 'UPLOADING', 'PROCESSING', 'PROCESSING_ERROR',
            'PENDING_MODERATION', 'PUBLISHED', 'REJECTED', 'HIDDEN', 'DELETED'
        )
    ),
    CONSTRAINT ck_material_duration CHECK (duration_ms IS NULL OR duration_ms >= 0),
    CONSTRAINT ck_material_version CHECK (media_version >= 1)
);

CREATE TABLE material_tag (
    material_id BIGINT NOT NULL,
    tag_id BIGINT NOT NULL,

    CONSTRAINT pk_material_tag PRIMARY KEY (material_id, tag_id),
    CONSTRAINT fk_material_tag_material FOREIGN KEY (material_id)
        REFERENCES material (id) ON DELETE CASCADE,
    CONSTRAINT fk_material_tag_tag FOREIGN KEY (tag_id)
        REFERENCES tag (id) ON DELETE CASCADE
);

CREATE TABLE transcript (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    material_id BIGINT NOT NULL,
    source_version INTEGER NOT NULL,
    language VARCHAR(20),
    full_text TEXT NOT NULL,
    subtitles_json TEXT NOT NULL,

    CONSTRAINT uq_transcript_material UNIQUE (material_id),
    CONSTRAINT fk_transcript_material FOREIGN KEY (material_id)
        REFERENCES material (id) ON DELETE CASCADE,
    CONSTRAINT ck_transcript_version CHECK (source_version >= 1)
);

CREATE TABLE processing_job (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    material_id BIGINT NOT NULL,
    source_version INTEGER NOT NULL,
    type VARCHAR(32) NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    attempts INTEGER NOT NULL DEFAULT 0,
    error_message TEXT,

    CONSTRAINT fk_processing_job_material FOREIGN KEY (material_id)
        REFERENCES material (id) ON DELETE CASCADE,
    CONSTRAINT ck_processing_job_type CHECK (
        type IN (
            'TRANSCODE', 'TRANSCRIBE', 'GENERATE_SUMMARY',
            'GENERATE_CHAPTERS', 'EXTRACT_ENTITIES', 'INDEX'
        )
    ),
    CONSTRAINT ck_processing_job_status CHECK (
        status IN ('PENDING', 'RUNNING', 'COMPLETED', 'FAILED')
    ),
    CONSTRAINT ck_processing_job_version CHECK (source_version >= 1),
    CONSTRAINT ck_processing_job_attempts CHECK (attempts >= 0)
);

CREATE INDEX idx_material_author ON material (author_id);
CREATE INDEX idx_material_status ON material (status);
CREATE INDEX idx_material_category ON material (category_id);
CREATE INDEX idx_material_tag_tag ON material_tag (tag_id);
CREATE INDEX idx_processing_job_material ON processing_job (material_id);
CREATE INDEX idx_processing_job_status ON processing_job (status);

--rollback DROP TABLE processing_job;
--rollback DROP TABLE transcript;
--rollback DROP TABLE material_tag;
--rollback DROP TABLE material;
--rollback DROP TABLE tag;
--rollback DROP TABLE category;
--rollback DROP TABLE app_user;
--rollback DROP TABLE media_asset;
